routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('materials', 'MaterialController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('groups', 'GroupController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('units', 'UnitController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::get('/', function () {
    return redirect(route('materials.index'));
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    public $timestamps = false;
    
    /**
     * Relation to parent group
     * 
     * @return \App\Models\Group
     */
    public function parentGroup()
    {
        return $this->belongsTo(Group::class, 'parent_id');
    }
    
    /**
     * Relation to materials
     * 
     * @return \Illuminate\Support\Collection
     */
    public function materials()
    {
        return $this->hasMany(Material::class, 'group_id');
    }
    
    /**
     * Save group model
     * 
     * @param array $input
     */
    public function saveGroup(array $input)
    {
        $this->name = $input['name'];
        $this->parent_id = isset($input['parent_id']) ? $input['parent_id'] : null;
        
        $this->saveOrFail();
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GroupRequest as Request;
use App\Models\Group;

class GroupController extends Controller
{
    protected $group;
    
    /**
     * @param \App\Models\Group $group
     */
    public function __construct(Group $group)
    {
        $this->group = $group;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = $this->group->all();
        
        return view('group.index', [
            'groups' => $groups,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groups = $this->group->all();
        
        return view('group.create', [
            'groups' => $groups,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->group->saveGroup($request->input());
            $message = 'success|Added';
        } catch(\Exception $ex) {
            $message = 'danger|Error';
        }
        
        return redirect()->back()->with('message', $message);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $group = $this->group->findOrFail($id);
        $groups = $this->group->where('id', '!=', $id)->get();
        
        return view('group.edit', [
            'group' => $group,
            'groups' => $groups,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $group = $this->group->findOrFail($id);
            $group->saveGroup($request->input());
            $message = 'success|Updated';
        } catch(\Exception $ex) {
            $message = 'danger|Error';
        }
        
        return redirect()->back()->with('message', $message);
    }
}

resources/views/group/forms/group.blade.php
<form method="post" action="{{ isset($group) ? route('groups.update', ['id' => $group->getKey()]) : route('groups.store') }}">
    {{ csrf_field() }}
    
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : null }}" id="name" name="name" value="{{ isset($group) ? $group->name : null }}" required>
                {!! $errors->has('name') ? '<div class="invalid-feedback">' . $errors->first('name') . '</div>' : null !!}
            </div>
        </div>
        
        <div class="col-sm-6">
            <div class="form-group">
                <label for="parent_id">Parent</label>
                <select class="form-control {{ $errors->has('parent_id') ? 'is-invalid' : null }}" name="parent_id" id="parent_id">
                    <option value="">(select)</option>
                    @foreach($groups as $item)
                        <option value="{{ $item->getKey() }}" {{ isset($group) && $group->parent_id == $item->getKey() ? 'selected' : null }}>{{ $item->name }}</option>
                    @endforeach
                </select>
                {!! $errors->has('parent_id') ? '<div class="invalid-feedback">' . $errors->first('parent_id') . '</div>' : null !!}
            </div>
        </div>
    </div>
    
    @if(isset($group)) 
        <button type="submit" name="_method" value="put" class="btn btn-primary">Update</button>
    @else
        <button type="submit" class="btn btn-success">Add</button>
    @endif
</form>