routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('materials', 'MaterialController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('groups', 'GroupController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('units', 'UnitController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::get('/', function () {
    return redirect(route('materials.index'));
});

app/Models/Group.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    public $timestamps = false;
    
    /**
     * Relation to parent group
     * 
     * @return \App\Models\Group
     */
    public function parentGroup()
    {
        return $this->belongsTo(Group::class, 'parent_id');
    }
    
    /**
     * Relation to materials
     * 
     * @return \Illuminate\Support\Collection
     */
    public function materials()
    {
        return $this->hasMany(Material::class, 'group_id');
    }
    
    /**
     * Save group model
     * 
     * @param array $input
     */
    public function saveGroup(array $input)
    {
        $this->name = $input['name'];
        $this->parent_id = isset($input['parent_id']) ? $input['parent_id'] : null;
        
        $this->saveOrFail();
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\GroupRequest as Request;
use App\Models\Group;

class GroupController extends Controller
{
    protected $group;
    
    /**
     * @param \App\Models\Group $group
     */
    public function __construct(Group $group)
    {
        $this->group = $group;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = $this->group->all();
        
        return view('group.index', [
            'groups' => $groups,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $groups = $this->group->all();
        
        return view('group.create', [
            'groups' => $groups,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->group->saveGroup($request->input());
            $message = 'success|Added';
        } catch(\Exception $ex) {
            $message = 'danger|Error';
        }
        
        return redirect()->back()->with('message', $message);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $group = $this->group->findOrFail($id);
        $groups = $this->group->where('id', '!=', $id)->get();
        
        return view('group.edit', [
            'group' => $group,
            'groups' => $groups,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $group = $this->group->findOrFail($id);
            $group->saveGroup($request->input());
            $message = 'success|Updated';
        } catch(\Exception $ex) {
            $message = 'danger|Error';
        }
        
        return redirect()->back()->with('message', $message);
    }
}

resources/views/group/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-header mb-5">
        <h1>Create new group</h1>
    </div>

    @include('group.forms.group')
@endsection

resources/views/group/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-header mb-5">
        <h1>Edit group - {{ $group->name }}</h1>
    </div>

    @include('group.forms.group')
@endsection

resources/views/group/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="page-header mb-5">
        <h1>Groups</h1>
        <a href="{{ route('groups.create') }}" class="btn btn-primary">Add new group</a>
    </div>

    <ul>
        @foreach($groups as $item)
            <li>
                <a href="{{ route('groups.edit', ['id' => $item->getKey()]) }}">
                    {{ $item->name }}
                    {{ isset($item->parentGroup) ? '(parent: ' . $item->parentGroup->name . ')' : null }}
                </a>
            </li>
        @endforeach
    </ul>
@endsection