routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('materials', 'MaterialController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('groups', 'GroupController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('units', 'UnitController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::get('/', function () {
    return redirect(route('materials.index'));
});

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    public $timestamps = false;
    
    /**
     * Relation to materials
     * 
     * @return \Illuminate\Support\Collection
     */
    public function materials()
    {
        return $this->hasMany(Material::class, 'unit_id');
    }
    
    /**
     * Save unit model
     * 
     * @param array $input
     */
    public function saveUnit(array $input)
    {
        $this->name = $input['name'];
        $this->shortcut = $input['shortcut'];
        
        $this->saveOrFail();
    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UnitRequest as Request;
use App\Models\Unit;

class UnitController extends Controller
{
    protected $unit;
    
    /**
     * @param \App\Models\Unit $unit
     */
    public function __construct(Unit $unit)
    {
        $this->unit = $unit;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $units = $this->unit->all();
        
        return view('unit.index', [
            'units' => $units,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('unit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $this->unit->saveUnit($request->input());
            $message = 'success|Added';
        } catch(\Exception $ex) {
            $message = 'danger|Error';
        }
        
        return redirect()->back()->with('message', $message);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $unit = $this->unit->findOrFail($id);
        
        return view('unit.edit', [
            'unit' => $unit,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $unit = $this->unit->findOrFail($id);
            $unit->saveUnit($request->input());
            $message = 'success|Updated';
        } catch(\Exception $ex) {
            $message = 'danger|Error';
        }
        
        return redirect()->back()->with('message', $message);
    }
}

resources/views/unit/forms/unit.blade.php
<form method="post" action="{{ isset($unit) ? route('units.update', ['id' => $unit->getKey()]) : route('units.store') }}">
    {{ csrf_field() }}
    
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : null }}" id="name" name="name" value="{{ isset($unit) ? $unit->name : null }}" required>
                {!! $errors->has('name') ? '<div class="invalid-feedback">' . $errors->first('name') . '</div>' : null !!}
            </div>
        </div>
        
        <div class="col-sm-6">
            <div class="form-group">
                <label for="shortcut">Shortcut</label>
                <input type="shortcut" class="form-control {{ $errors->has('shortcut') ? 'is-invalid' : null }}" id="shortcut" name="shortcut" value="{{ isset($unit) ? $unit->shortcut : null }}" required>
                {!! $errors->has('shortcut') ? '<div class="invalid-feedback">' . $errors->first('shortcut') . '</div>' : null !!}
            </div>
        </div>
    </div>
    
    @if(isset($unit)) 
        <button type="submit" name="_method" value="put" class="btn btn-primary">Update</button>
    @else
        <button type="submit" class="btn btn-success">Add</button>
    @endif
</form>