routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('materials', 'MaterialController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('groups', 'GroupController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::resource('units', 'UnitController', [
    'except' => [
        'show',
        'destroy',
    ],
]);

Route::get('/', function () {
    return redirect(route('materials.index'));
});

resources/views/layouts/app.blade.php
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>Materials</title>
    </head>
    
    <body>
        <div class="container">
            <ul class="nav mt-3">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('materials.index') }}">Materials</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('groups.index') }}">Groups</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('units.index') }}">Units</a>
                </li>
            </ul>
            
            <hr />
            
            {!! displayFlashMessage() !!}

            @yield('content')
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>